# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        list1 = ''.join(sorted(s))
        list2 = ''.join(sorted(t))
        
        for i in range(len(list2)):
            if i >= len(list1) and list2[i] or i<len(list1) and list2[i] != list1[i]:
                return list2[i]